"""empty message

Revision ID: 74843efaa3e0
Revises: 41ff54751aec
Create Date: 2024-08-08 15:50:11.316874

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74843efaa3e0"
down_revision = "41ff54751aec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dummy_model")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="dummy_model_pkey"),
    )
    # ### end Alembic commands ###
